apiVersion: apps/v2  
kind: Deploymennt
metadata:
  name: my-app
  namespace: defautl
spec:
  replicas: two  
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: nginx:latest
          ports:
            - containerPort: "80"
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: my-config  
                  key: db-url
