# Default values for python-app
replicaCount: 1

image:
  repository: "022499010678.dkr.ecr.us-east-1.amazonaws.com/python"
  tag: "latest"
  pullPolicy: IfNotPresent


service:
  type: NodePort   # Specify NodePort type
  port: 80
  nodePort: 30007  # Optional: Specify a node port (must be between 30000-32767)

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}
